import Preloader from "@/layout/Preloader";
import "@css/bootstrap.min.css";
import "@css/font-awesome-pro.css";
import "@css/fxotary-icon.css";
import "@css/responsive.css";
import "@css/slick.css";
import "@css/spacing.css";
import "@css/style.css";
import "./globals.css";

export const metadata = {
  title: "Fxotary - Digital Agency React NextJS Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Preloader />
        {children}
      </body>
    </html>
  );
}
